### ISSUE TITLE
ImportError when running on gitpod

### ISSUE THREAD

**Issue by andreale28** [petehunt/poor-mans-data-lake#3]
Hi all, I have followed your [Poor man data lake](https://dagster.io/blog/duckdb-data-lake) tutorial but encounter this error/bug when run dagit ,
` ImportError: cannot import name 'introspection_query' from 'graphql' (/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/graphql/__init__.py).`  

However, according to tutorial, dagster should run properly. 

Are there any fixes for this? I have looked around but still not found any solutions.

**Comment by andreale28** [comment]
Traceback error:
`Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/3.8.13/bin/dagit", line 5, in <module>
    from dagit.cli import main
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/cli.py", line 21, in <module>
    from .app import create_app_from_workspace_process_context
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/app.py", line 11, in <module>
    from .webserver import DagitWebserver
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/webserver.py", line 7, in <module>
    from dagster_graphql import __version__ as dagster_graphql_version
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/__init__.py", line 3, in <module>
    from .client import (
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/client/__init__.py", line 1, in <module>
    from .client import DagsterGraphQLClient
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/client/client.py", line 5, in <module>
    from gql import Client, gql
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/gql/__init__.py", line 2, in <module>
    from .client import Client
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/gql/client.py", line 3, in <module>
    from graphql import parse, introspection_query, build_ast_schema, build_client_schema
ImportError: cannot import name 'introspection_query' from 'graphql' (/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/graphql/__init__.py)`

**Comment by andreale28** [comment]
Traceback error when running `dagit`

> Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/3.8.13/bin/dagit", line 5, in <module>
    from dagit.cli import main
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/cli.py", line 21, in <module>
    from .app import create_app_from_workspace_process_context
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/app.py", line 11, in <module>
    from .webserver import DagitWebserver
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagit/webserver.py", line 7, in <module>
    from dagster_graphql import __version__ as dagster_graphql_version
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/__init__.py", line 3, in <module>
    from .client import (
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/client/__init__.py", line 1, in <module>
    from .client import DagsterGraphQLClient
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster_graphql/client/client.py", line 5, in <module>
    from gql import Client, gql
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/gql/__init__.py", line 2, in <module>
    from .client import Client
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/gql/client.py", line 3, in <module>
    from graphql import parse, introspection_query, build_ast_schema, build_client_schema
ImportError: cannot import name 'introspection_query' from 'graphql' (/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/graphql/__init__.py)

**Comment by petehunt** [comment]
i "fixed" this in 2de3e3fb8ffb4d73aa6290f4e2add774f5f2e050
